site_name: ECNN - Embedded Convolutional Neural Network
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tracking

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
      
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true  
  - footnotes
  - tables
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search
  - markdown-exec
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav: 
  - Introdução: index.md
  - Contexto: context.md
  - Inputs e Outputs: inputs_outputs.md
  - Model type: model_type.md
  - Camada de convolução (Encoder): convolutional_layers.md
  - Camada de convolução transposta (Encoder): transposed_convolutional_layers.md
  - Camadas de embedding: embedding_layers.md
  - Normalização em batches: batch_normalizer.md
  - Dilatação: dilation_layers.md
  - Função de ativação: activation_function.md
  - Layout U-Net: unet.md
  - Função de perda: loss_function.md
  - Otimizador: optimizer.md
  - Gradient Descendente: gradient_descent.md
  - Forward e Back-propagation: forward_backward.md
  - Batches e Epochs: batches_epochs.md
  - Multiprocessamento: multiprocessing.md
  - Teste: test.md